name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-26.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Lix
        uses: canidae-solutions/lix-quick-install-action@v4

      - name: Run tests
        run: nix develop .#default --command just test
